### PR TITLE
log creation updates

### LINKED ISSUE #602: Unable to execute anonymous apex from Mavensmate App project.
I am trying to run some anonymous apex after opening a project in the Mavensmate App but am receiving this error: `Could not create Trace Flags: LogType is required.` I'm not sure if I need to set a log type somewhere or what. Any help will be greatly appreciated.

I am running app version 0.0.10 on Windows. Here are the relevant logs:

```
2015-11-12T15:46:59.872Z - info: 

==================> executing command: start-logging

2015-11-12T15:46:59.872Z - info: executeCommandForProject payload is: null
2015-11-12T15:46:59.872Z - debug: command class is: StartLoggingCommand
2015-11-12T15:46:59.875Z - debug: attempting to start logging for: 
2015-11-12T15:46:59.875Z - debug:  0=005G0000003pal8IAA
2015-11-12T15:46:59.875Z - debug: expiring: 1447372019873
2015-11-12T15:47:00.200Z - debug: attempting to delete trace flags: 
2015-11-12T15:47:00.200Z - debug: 
2015-11-12T15:47:00.201Z - debug: deleted trace flags
2015-11-12T15:47:00.201Z - debug: 
2015-11-12T15:47:00.201Z - debug: attempting to create trace flags
2015-11-12T15:47:00.514Z - info: handling command result: 
2015-11-12T15:47:00.514Z - error:  Error: Could not create Trace Flags: LogType is required.: LogType
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\sfdc-client.js:931:20
    at C:\Program Files\MavensMate\resources\app\node_modules\promise\lib\core.js:33:15
    at flush (C:\Program Files\MavensMate\resources\app\node_modules\asap\asap.js:27:13)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
```

### PR DESCRIPTION
**Pull request by ralphcallaway**
1. add support for trace logs for api version 35+ (fixes https://github.com/joeferraro/MavensMate-app/issues/66, fixes https://github.com/joeferraro/MavensMate-app/issues/105)
2. update debug user id when updating org credentials (fixes #602)

Notes:
- this is a re-submission of pr #606 after getting my fork setup correctly
- includes some whitespace cleanup, turn off whitespace (`w=1` in url) for best viewing of this PR

### CODE REVIEW

**Comment by omniphx** [comment]
Any update on when this could be released? Currently, the only way to get debug logs to work is to switch back to v34. Would be nice to do development on the latest version

**Comment by ralphcallaway** [comment]
@omniphx not sure about release timing, it can vary depending on how much time the contributors are spending at their day job ;)

short term, it's pretty quick to set up a dev version, see #518 for details

**Comment by omniphx** [comment]
Thanks @ralphcallaway, I'll give that a try! Let me know if there's anything I can help with

**Comment by ralphcallaway** [comment]
@omniphx always looking for help :)

things that are particular useful
- pull requests with bug fixes
- pull requests with expanded tests
- getting people to provide enough details to reproduce bugs (e.g. my reply to #614)

@joeferraro anything other suggestions for how people can help out?

**Comment by yippie** [comment]
Is this pull request waiting on fixed unit tests before it can be released?

**Comment by ralphcallaway** [comment]
@yippie no, it's waiting on free time to do another release (typically they'll be a big push for bug fixes and pull request merges)

@joeferraro any idea when the next release might be coming?

**Comment by joeferraro** [comment]
@ralphcallaway i've cherry-picked from this PR, apologies in advance. Got way behind on this and the cost to merge outweighed the benefits given logging was refactored recently.

**Pull request closed without merging**
