### PR TITLE
adding 'prompt=login' to oAuth request to force a login prompt

### PR DESCRIPTION
**Pull request by ChuckJonas**
Possible fix for #752.   Forces login prompt when adding new project.

### CODE REVIEW

**Comment by ChuckJonas** [comment]
FYI: I was able to reproduce the variation of the issue as describe by @fracarma and tested that this fixes it.  

I was unable to reproduce the issue as I described it, but hoping this will fix that as well.  Unsure if any functions other than "new project" use this endpoint so that's all I tested.

**Comment by joeferraro** [comment]
@ChuckJonas so this basically forces the Salesforce OAuth servers to ignore any cookies you might have? If so, I like this solution better than my approach, which is to have Desktop manage (delete) Salesforce cookies.

**Comment by ChuckJonas** [comment]
@joeferraro I'm pretty sure it just forces the user to login, no matter what active sessions they have in place.  Scroll down to the `prompt` parameter in this [documentation](https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_web_server_flow.htm&language=en_US) for more info.  

There is also an `select_account` option that might be more convenient to the user (Assuming it gives you a option to login with a different account).  I didn't try it because the documentation was ambiguous.

**Comment by ChuckJonas** [comment]
@joeferraro closing this one and resubmitting from a new branch so I can regain my master branch (because I'm dumb)

**Pull request closed without merging**
