### PR TITLE
potential fix for credential load bugs

### PR DESCRIPTION
**Pull request by ralphcallaway**
this can manifest in a couple different ways, so can't say for sure, but appears like a potential fix for these issues
- https://github.com/joeferraro/MavensMate/issues/595
- https://github.com/joeferraro/MavensMate/issues/598
- https://github.com/joeferraro/MavensMate/issues/592
- https://github.com/joeferraro/MavensMate-SublimeText/issues/719
- https://github.com/joeferraro/MavensMate-SublimeText/issues/670

### CODE REVIEW

**Comment by ralphcallaway** [comment]
@joeferraro any objections to merging this pending circle ci test results?

**Comment by joeferraro** [comment]
@ralphcallaway thanks for this. let me have a review today/tomorrow only because the changes are on project.js which is such a fundamental module

**Comment by ralphcallaway** [comment]
@joeferraro thanks for taking a look

**Comment by ralphcallaway** [comment]
@joeferraro looking good? this takes care of 3-4 open issues :)

**Pull request merged**
